issues-468: remove status-only fields from required sections of spec api
nutanix/papiea pull request #489
Opened 2020-08-27 14:21 UTC by NikitaChernenkoNutanix

When a field is marked as 'status-only" it doesn't appear in required fields for spec anymore

2020-08-27 14:48 UTC, Emulebest requested changes
The changes are good, some minor comments. In addition, It would be beneficial if you could add the test to see that these changes don't modify `spec-only` fields that are required

2020-08-27 14:48 UTC, Emulebest commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +                const fieldsToRemove: String[] = []
not `String[]` but `string[]`

2020-08-27 14:48 UTC, Emulebest commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +            if (typeof schema[prop] === 'object' && "required" in schema[prop] && "properties" in schema[prop]) {
I'd rather use `hasOwnProperty()` than `in` because it has more security guarantees

2020-08-27 14:48 UTC, Emulebest commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +            this.clearSchemaField(kindSchema, "status-only")
See comment above please

2020-08-27 14:52 UTC, Emulebest commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +            this.clearSchemaField(kindSchema, "status-only")
For some reason the comment regarding `clearSchemaField` wasn't saved, so posting it here.

Could we expand the function `clearSchemaField` to just 2 calls in place here? I don't see it used in any other places and the semantics of `clear` doesn't really imply removing `required` fields

2020-08-27 15:09 UTC, Emulebest requested changes

2020-08-27 15:09 UTC, Emulebest commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +                    const field = properties[name];
really minor but we generally decided to avoid semicolon `;` in new code pieces

2020-08-27 15:17 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +                const fieldsToRemove: String[] = []
done

2020-08-27 15:17 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +            if (typeof schema[prop] === 'object' && "required" in schema[prop] && "properties" in schema[prop]) {
done

2020-08-27 15:17 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +            this.clearSchemaField(kindSchema, "status-only")
done

2020-08-27 15:18 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/api_docs/api_docs_generator.ts
> +                    const field = properties[name];
done

2020-08-27 15:18 UTC, Emulebest approved these changes

2020-08-27 16:04 UTC, shlomi-nx commented on papiea-engine/__tests__/docs_tests/api_docs.test.ts
> +        structure.properties.x["x-papiea"] = "spec-only"
There is no `spec-only` field attribute, only a `spec-only` entity. We should probably throw an error on this.

2020-08-28 07:52 UTC, Emulebest commented on papiea-engine/__tests__/docs_tests/api_docs.test.ts
> +        structure.properties.x["x-papiea"] = "spec-only"
Also, I think we need to add a check that we don't have any `status-only` fields on `spec-only` entities

2020-08-31 10:22 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/docs_tests/api_docs.test.ts
> +        structure.properties.x["x-papiea"] = "spec-only"
I've added 2 additional steps during validation of provider:
1) check that the value of x-papiea is ["status-only'] (as these are all possible values for now)
2) check that if an entity is a spec-only entity, x-papiea can be only one of [""] (as these are all possible values except status-only)

2020-08-31 10:46 UTC, Emulebest requested changes
Overall, changes are good, some code style comments

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/test_data_factory.ts
> +}
What is the necessity for this function, isn't it an alias to `getLocationDataDescription()`?

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/test_data_factory.ts
> +}
Please use the builder pattern instead (e.g. https://github.com/nutanix/papiea/blob/7a6ac84147f379335d72a282c658651ccb129d84/papiea-engine/__tests__/test_data_factory.ts#L256), I think it is too much of little function with overly long names.

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/test_data_factory.ts
> +}
see the comment above

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +        }).not.toThrow()
Nitpicking, but `.not.toThrow()` could be expressed without any expects

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +        // xPapieaField pryoperty have only statusOnlyValue value
typo

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +    }
This one is good! I would change the name of the function to `validateXPapieaMark` or similar, since `validateFieldValue` is too general for what this function does

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +        const statusOnlyValue = "status-only"
If these are constant, I'd rather add a constant or enum (choose appropriate) for these field names

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +        const xPapieaField = "x-papiea"
Same as above

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate spec only kind structure with spec-only value x-papiea field", async () => {
should it pass, should it fail? Hard to wrap the head around :). Please add the expected outcome

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate spec only kind structure with status-only value x-papiea field", async () => {
Same as above

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate correct spec only kind structure", async () => {
Same as above

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then((e) => done.fail()).catch(() => done());
Please use the `try catch(e)` or `expect.toThrow` format in new code, thanks

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then(() => done.fail()).catch(() => done());
Please use the try catch(e) or expect.toThrow format in new code, thanks

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then(() => done()).catch(() => done.fail());
Please use the try catch(e) or expect.toThrow format in new code, thanks

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +        const statusOnlyValue = "status-only"
Possible values should be a data structure of its own (array, enum, etc.)

2020-08-31 10:46 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +    validateSpecOnlyStructures(entity: Data_Description) {
`validateSpecOnlyStructure` (without letter S, since we are not working with collections here)
This is not a very good OOP practice, since it is very specific, but I think that we could leave that for now. Maybe we could rethink this as we have more cases like `spec-only` stuff

2020-08-31 13:48 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/test_data_factory.ts
> +}
getLocationDataDescription() provides incorrect structure - spec-only entity with status-only fields.
I'd refactor it to correct structure, but it's used throughout the project so I decided to make it obvious what kind of data is provided by the function.

2020-08-31 13:50 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/validator/index.ts
> +    }
the function is currently abstract and is not bound to a specific field and specific possible values, I'd keep it as it is as it can't be reused so.

2020-08-31 13:51 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate spec only kind structure with status-only value x-papiea field", async () => {
will do

2020-08-31 13:51 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate correct spec only kind structure", async () => {
will do

2020-08-31 13:51 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then((e) => done.fail()).catch(() => done());
will do

2020-08-31 13:51 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then(() => done.fail()).catch(() => done());
will do

2020-08-31 13:52 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then(() => done()).catch(() => done.fail());
will do

2020-08-31 13:54 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/validator/index.ts
> +    validateSpecOnlyStructures(entity: Data_Description) {
I'm open to alternative approaches to the function. We have a specific logic for spec-only structures so it seems to be an easy solution for now.

2020-08-31 14:00 UTC, Emulebest commented on papiea-engine/__tests__/test_data_factory.ts
> +}
I see... This should be handled. Since updating the status of `spec-only` entity is already an error, then I'd remove the
```
    z:
      type: number
      x-papiea: status-only
```
and see if tests do fail. I don't think many will do

2020-08-31 14:03 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +    }
The problem is that the function doesn't validate the value itself, it only validates the entity sort of metadata portion (`x-papiea` stuff)

2020-08-31 15:56 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/test_data_factory.ts
> +}
we have withKinds in the builder already. we need to provide the appropriate kind to it.
in order to do so, I introduced 
https://github.com/nutanix/papiea/blob/issue-468-spec-remove-status-only-fields-from-required/papiea-engine/__tests__/test_data_factory.ts#L110
and https://github.com/nutanix/papiea/blob/issue-468-spec-remove-status-only-fields-from-required/papiea-engine/__tests__/test_data_factory.ts#L81

2020-08-31 16:30 UTC, Emulebest commented on papiea-engine/__tests__/test_data_factory.ts
> +}
related to #492

2020-09-01 07:43 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/test_data_factory.ts
> +}
thanks for resolving it!

2020-09-01 07:44 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/test_data_factory.ts
> +}
Seems like a good solution

2020-09-01 08:42 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate spec only kind structure with spec-only value x-papiea field", async () => {
done

2020-09-01 08:42 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate correct spec only kind structure", async () => {
done

2020-09-01 08:42 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/validation_tests/validation.test.ts
> +    test("Validator validate spec only kind structure with status-only value x-papiea field", async () => {
done

2020-09-01 09:13 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then(() => done()).catch(() => done.fail());
done

2020-09-01 09:13 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then(() => done.fail()).catch(() => done());
done

2020-09-01 09:13 UTC, NikitaChernenkoNutanix commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +        providerApi.post('/', provider).then((e) => done.fail()).catch(() => done());
done

2020-09-01 09:26 UTC, NikitaChernenkoNutanix commented on papiea-engine/src/validator/index.ts
> +    }
renamed xPapieaValue to value, changed camelCase to snake_case

2020-09-01 09:52 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +        const statusOnlyValue = "status-only"
Since there is only one case for now `status-only` let's leave it as is

2020-09-01 09:53 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +    }
Since function doesn't feature `xPapiea...` stuff, we can assume it is general enough

2020-09-01 09:53 UTC, Emulebest approved these changes

2020-09-01 09:54 UTC, merged