Nitesh/add python sdk tests
nutanix/papiea pull request #495
Opened 2020-09-03 19:36 UTC by nitesh-idnani1

This PR tracks the python sdk tests development.

2020-09-16 05:42 UTC, shlomi-nx reviewed
Good start!

2020-09-16 05:42 UTC, shlomi-nx commented on papiea-sdk/python/__tests__/kinds/object_kind.yml
> +    x-papiea-entity: basic
Why is this a `basic` entity? I would make it a differ an implement some `on` intentful handlers.

2020-09-18 00:52 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/kinds/object_kind.yml
> +    x-papiea-entity: basic
Yeah, just kept it to start with. Changed it now, thanks

2020-09-21 15:05 UTC, Emulebest reviewed
Current tests are looking good! @nitesh-idnani1 are you still working on pushing e2e (issue-based) tests because I don't see those here?

2020-09-21 15:05 UTC, Emulebest commented on papiea-sdk/python/papiea/utils.py
> +    )
Can we type it out?

2020-09-21 15:05 UTC, Emulebest commented on papiea-sdk/python/tests/sdk_test.py
> +            user_info={"owner": "nitesh", "tenant": "ada14b27-c147-4aca-9b9f-7762f1f48426"},
Please anonymize these, thanks!

2020-09-30 23:13 UTC, joshua-berry-ntnx requested changes
This PR needs to be broken up into multiple PRs I think. I'm seeing engine/core changes happening in a PR that's ostensibly only about tests, and I see we have two different sets of tests going in at once. (BTW, what is the difference between `__tests__` and `tests`? I see we have both and there are similarly named-files in each, yet different sets of tests...)

And while I was in the process of reviewing this, I saw a new commit get added which adds new APIs to the SDK for intent watchers (again, unrelated to the original PR description). So I'm going to pause reviewing for now—I think we need to maybe step back and look at how we can better-organize these changes and the code. Let's discuss in tomorrow's meeting.

2020-09-30 23:13 UTC, joshua-berry-ntnx commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +async def ensure_bucket_exists_handler(ctx, input_bucket_name):
If these and the other `_handler` functions are all procedures, we should just give them the same name as the procedure (no need to append `handler`, which might get confused with "intent handler").

2020-09-30 23:13 UTC, joshua-berry-ntnx commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +            object_uuid_set.add(obj.reference.uuid)
There is no need to do all this yourself. Papiea will give you the diff for each individual change in the `diff` parameter. I can point you to an example of this offline in the BMaaS codebase (won't put the link here since Papiea is open source and BMaaS isn't).

2020-09-30 23:13 UTC, joshua-berry-ntnx commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +            entity_object = await object_entity_client.get(AttributeDict(uuid=diff[0].status[0].reference.uuid))
You may get more than one diff in a single `removed` call.

2020-09-30 23:13 UTC, joshua-berry-ntnx commented on papiea-sdk/python/papiea/client.py
> +            raise ex
What are all of these client changes? I thought this PR was about adding test cases.

2020-09-30 23:13 UTC, joshua-berry-ntnx commented on papiea-sdk/python/tests/test_data/location_kind_test_data.yml
> +Location:
I'm confused what these location YAML files are for. We have the bucket/object provider; why are they necessary?

2020-09-30 23:28 UTC, nitesh-idnani1 commented on papiea-engine/Dockerfile
> +    && add-apt-repository ppa:deadsnakes/ppa -y \
We have a requirement of python version > 3.7, but we can find a workaround to avoid PPAs

2020-09-30 23:30 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/kinds/bucket_kind.yml
> +                        description: Name of the object within the bucket
Added reference in utils.setup_kinds function since they use ref_type (python function) to assign reference type.

2020-09-30 23:30 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/kinds/object_kind.yml
> +                        description: Name of the object which refers to this object
Added bucket_reference in utils.setup_kinds function since they use ref_type (python function) to assign reference type.

2020-09-30 23:35 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +async def ensure_bucket_exists_handler(ctx, input_bucket_name):
Got it

2020-09-30 23:36 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +    # assuming input_object to be the object name and the uid
Done

2020-09-30 23:41 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +    # assuming input_object to be the object name and the uid
Yeah, fixed it. Thanks

2020-09-30 23:45 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +                entity_bucket.spec.objects[:] = [d for d in entity_bucket.spec.objects if d.get("name") != input_object.object_name]
Got it

2020-09-30 23:46 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +            object_uuid_set.add(obj.reference.uuid)
Sure, let's discuss this.

2020-09-30 23:59 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +            entity_object = await object_entity_client.get(AttributeDict(uuid=diff[0].status[0].reference.uuid))
Ohh missed this sorry. Fixed it, need to understand the indexing for the spec and status though. I did not understand that.

2020-10-01 00:04 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/utils.py
> +    async with papiea_test.get_client(papiea_test.OBJECT_KIND) as object_entity_client:
Fixed

2020-10-01 00:08 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/utils.py
> +        )
Done

2020-10-01 00:22 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/utils.py
> +            raise ex
Okay, will fix this wherever required

2020-10-01 00:22 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/utils.py
> +            raise Exception("Cleanup operation failed")
Got it, I see the problem. Thanks

2020-10-01 00:23 UTC, nitesh-idnani1 commented on papiea-sdk/python/tests/sdk_test.py
> +            user_info={"owner": "nitesh", "tenant": "ada14b27-c147-4aca-9b9f-7762f1f48426"},
Done

2020-10-01 00:25 UTC, nitesh-idnani1 commented on papiea-sdk/python/tests/test_data/location_kind_test_data.yml
> +Location:
This YAML is in the tests folder which includes a bunch of tests ported from the typescript sdk tests. All the discusses e2e tests are in the __tests__ folder (I'll rename __tests__ to e2e_tests for clarification). Thanks for pointing this out

2020-10-01 00:30 UTC, nitesh-idnani1 commented on papiea-sdk/python/papiea/client.py
> +            raise ex
We can move this to a separate PR or commit to clean this up. Here, I've implemented a get_all function to fetch all the entities for a particular kind and added exception handling for the operations

2020-10-01 17:43 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedures/create_object_input.yml
> +    description: Name of the object to be created
Done

2020-10-02 11:50 UTC, Emulebest requested changes
Looks good, some minor comments

2020-10-02 11:50 UTC, Emulebest commented on papiea-sdk/python/__tests__/utils.py
> +async def setup_and_register_sdk() -> ProviderServerManager:
Agree with the points above

2020-10-02 11:50 UTC, Emulebest commented on papiea-sdk/python/__tests__/utils.py
> +            raise Exception("Cleanup operation failed")
For Typescript SDK we have this https://github.com/nutanix/papiea/blob/20681fb4792cfdbded85ea83b2bc78ef8c5ae05f/papiea-sdk/typescript/src/provider_sdk/typescript_sdk_exceptions.ts#L3. 
Can't recall if we have the same for the Python one but this semantics is exactly what you need here

2020-10-02 11:50 UTC, Emulebest commented on papiea-sdk/python/papiea/client.py
> +            raise ex
This is too much boilerplate to be copy pasting around. Please see this https://github.com/nutanix/papiea/blob/20681fb4792cfdbded85ea83b2bc78ef8c5ae05f/papiea-client/src/entity_client.ts#L16

2020-10-05 20:00 UTC, nitesh-idnani1 commented on papiea-sdk/python/__tests__/procedure_handlers.py
> +    return EntityReference(uuid="", kind="", message="Unable to unlink object entity")
Yes, in case of reaching the end of code without success, I cannot return a None object since the validation function expects a valid YAML structure in the return value if there's no exception. We can discuss another approach for this, I've started this as a placeholder for now.

2020-10-13 09:15 UTC, Emulebest requested changes

2020-10-13 09:15 UTC, Emulebest commented on papiea-sdk/python/papiea/api.py
> +        except (ConflictingEntityException, EntityNotFoundException, PermissionDeniedException, ProcedureInvocationException, UnauthorizedException, ValidationException, BadRequestException, PapieaSe
The exception list you specified here isn't going to be raised automatically, you need to do this manually:
```
try:
    return await self.call(method, prefix, data, headers)
except:
    if e?.response?.data?.error.type == PapieaError.ConflictingEntity: # Note this is not the correct syntax, this should give you a general idea
        raise ConflictingEntityError(e.response.data.error.message, e)
```
Take a look at switch case here https://github.com/nutanix/papiea/blob/d45c0cb1cbc1ddcafa88ce7feeb28d575be6352b/papiea-client/src/entity_client.ts#L20

2020-10-13 09:15 UTC, Emulebest commented on papiea-sdk/python/e2e_tests/sdk_test.py
> +            assert str(ex) == "Entity with kind: object, uuid: shouldfailuuid not found"
The error string seems kind of messy, can we make it better?

2020-10-13 19:18 UTC, nitesh-idnani1 commented on papiea-sdk/python/e2e_tests/sdk_test.py
> +            assert str(ex) == "Entity with kind: object, uuid: shouldfailuuid not found"
Fixed it

2020-10-13 19:19 UTC, nitesh-idnani1 commented on papiea-sdk/python/papiea/api.py
> +        except (ConflictingEntityException, EntityNotFoundException, PermissionDeniedException, ProcedureInvocationException, UnauthorizedException, ValidationException, BadRequestException, PapieaSe
Yes, the exception formatting and raising part is handled by the "check_response" function in the "python_sdk_exceptions.py" file, and it is invoked by the "call" function above. So, we're getting the appropriate exception message within the "make_request" block.

2020-10-15 12:48 UTC, Emulebest commented on papiea-sdk/python/papiea/api.py
> +        except (ConflictingEntityException, EntityNotFoundException, PermissionDeniedException, ProcedureInvocationException, UnauthorizedException, ValidationException, BadRequestException, PapieaSe
Okay, got it

2020-10-15 12:49 UTC, Emulebest approved these changes
Looks good, let's add the tests to the CircleCI pipeline and merge

2020-10-20 08:48 UTC, Emulebest commented
> Looks good, let's add the tests to the CircleCI pipeline and merge

@nitesh-idnani1 any progress adding this to our CI pipeline? Do you require any help?

2020-10-20 16:56 UTC, nitesh-idnani1 commented
> > Looks good, let's add the tests to the CircleCI pipeline and merge
> 
> @nitesh-idnani1 any progress adding this to our CI pipeline? Do you require any help?

Yes, I've added python installation steps and the pytest cmd in the pipeline. Everything is working fine and we can merge this now.

2020-10-21 01:00 UTC, nitesh-idnani1 commented
@Ntnx-Igor-Korotach  Also verified a failed sdk test in the pipeline and got the expected result. We can merge this now.

2020-10-21 10:35 UTC, merged