Added papiea customization via file config
nutanix/papiea pull request #510
Opened 2020-09-28 14:20 UTC by Emulebest

resolves #503

2020-09-28 17:58 UTC, joshua-berry-ntnx requested changes

2020-09-28 17:58 UTC, joshua-berry-ntnx commented on README.md
> +The configuration parameters are following:
This might be a style thing but can we use YAML for the config file instead? I know people tend to have strong opinions about YAML, but YAML allows for comments, and I think being able to leave comments in a config file is really really important (moreso than any stylistic objections).

To illustrate the point, your example below is not valid JSON. ;)

2020-09-28 17:58 UTC, joshua-berry-ntnx commented on papiea-engine/src/utils/arg_parser.ts
> +}
Very nice. :) Can I suggest clubbing this with the interface definition above and mapping the FN_MAP to the corresponding type? Something like:

```ts
const TRANSFORM_FN_MAP = {...} as const;
export type PapieaConfig = {
    [k in keyof (typeof TRANSFORM_FN_MAP)]: ReturnType<(typeof TRANSFORM_FN_MAP)[k]>,
};
```

Then you can avoid duplicating what are effectively two different type definitions--one for the transformations and one for the config object itself.

2020-09-28 17:58 UTC, joshua-berry-ntnx commented on papiea-engine/src/utils/arg_parser.ts
> +    debug: (val: string) => val === "true"
For these booleans, can I suggest checking for `not in [0, null, false, ""]` and their string equivalents instead? For environment variables, often people will do silly/stupid things like `PAPIEA_DEBUG=foo` and expect that because the variable is not the empty string, debug will be enabled (since many shell scripts are written this way).

2020-09-28 17:58 UTC, joshua-berry-ntnx commented on papiea-engine/src/utils/arg_parser.ts
> +    for (let key in config) {
Check all possible environment variables (including defaults), not just those specified in config. Conceptually, you want something like:

```ts
let result = {};
Object.assign(result, defaults, config, env_vars);
```

So if something is set in defaults but not config, it can still be overridden.

2020-09-29 06:08 UTC, Emulebest commented on README.md
> +The configuration parameters are following:
I don't mind having a YAML definition

2020-09-29 08:37 UTC, Emulebest commented on papiea-engine/src/utils/arg_parser.ts
> +    for (let key in config) {
Well, defaults are of type PapieaConfig, so they are expected to comply with config 100%

2020-09-29 08:39 UTC, Emulebest commented on papiea-engine/src/utils/arg_parser.ts
> +    debug: (val: string) => val === "true"
I didn't get the solution exactly, would you like us to check that `PAPIEA_DEBUG` is either `"true"` or `"false"` and nothing else?

2020-09-29 09:08 UTC, Emulebest commented on papiea-engine/src/utils/arg_parser.ts
> +}
Is it a valid TS code above? There are a few reasons I decided not to dive deep into the type system here:
1) We don't rely on TS types in runtime since we are using type erasure
2) The signature becomes needlessly complicated for any non inner circle maintainer

2020-09-30 12:32 UTC, Emulebest commented on papiea-engine/src/utils/arg_parser.ts
> +}
Found a simpler way of doing what you meant

2020-09-30 19:59 UTC, joshua-berry-ntnx commented on papiea-engine/src/utils/arg_parser.ts
> +    for (let key in config) {
I think you missed what I was trying to say—right now, let's say I have defaults like `{foo: 1, bar: 2}`. Now let's say I have a config `{foo: 42}` and an environment variable `PAPIEA_BAR=17`. The way the code is written today, the `PAPIEA_BAR` variable (which is intended to override `bar`) will be ignored because `bar` is not specified in the config.

We should make sure environment variables can directly override defaults without needing to be specified in the config.

2020-10-01 09:35 UTC, Emulebest commented on papiea-engine/src/utils/arg_parser.ts
> +    for (let key in config) {
Okay, got it

2020-10-01 11:59 UTC, merged