Nitesh/add intent watcher api
nutanix/papiea pull request #516
Opened 2020-10-01 22:02 UTC by nitesh-idnani1

This PR tracks the development of the IntentWatcher API within the python and typescript SDKs and it's related tests.

2020-10-02 12:18 UTC, Emulebest requested changes
Code wise - things are looking fine. Please remove some boilerplate taking inspirations from the example and move things to more appropriate places

2020-10-02 12:18 UTC, Emulebest commented on papiea-sdk/python/papiea/client.py
> +            raise
I don't get the purpose of this, any function in python can throw, this is just the nature of the language. Unlike Typescript all the awaited objects handle exceptions as well as the sync ones do https://docs.python.org/3/library/asyncio-dev.html#detect-never-retrieved-exceptions. Unlike Java, Python doesn't have the `throws` contract https://www.w3schools.com/java/ref_keyword_throws.asp or Ocaml's Algebraic Effects https://github.com/ocamllabs/ocaml-effects-tutorial.

If you are intending to make exceptions more descriptive and precise, please wrap function calls as decorators or https://github.com/nutanix/papiea/blob/20681fb4792cfdbded85ea83b2bc78ef8c5ae05f/papiea-client/src/entity_client.ts#L16

2020-10-02 12:18 UTC, Emulebest commented on papiea-sdk/python/papiea/python_sdk.py
> +            raise ex
See the comment above please

2020-10-02 12:18 UTC, Emulebest commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> +    IntentWatcherImpl,
This is a bad naming pattern, generally you don't want any `IntentWatcherI` or `IntentWatcherImpl` stuff

2020-10-02 12:18 UTC, Emulebest commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk_interface.ts
> +}
This is a bad naming pattern, generally you don't want any `IntentWatcherI` or `IntentWatcherImpl` stuff.
Moreover, this is not implementation :)

2020-10-02 12:18 UTC, Emulebest commented on papiea-sdk/typescript/__tests__/intentful_workflow_tests/intentful_workflow.test.ts
> +import { ProviderSdk, IntentWatcherApi } from "../../src/provider_sdk/typescript_sdk";
Isn't intent watcher more of a client thing? https://github.com/nutanix/papiea/tree/master/papiea-client/src is where it belongs IMO.
Note, we don't want Typescript `papiea-sdk` depending on `papiea-client` so I wouldn't make any changes in test files

2020-10-08 09:23 UTC, Emulebest requested changes
LGTM, a few comments

2020-10-08 09:23 UTC, Emulebest commented on papiea-sdk/python/e2e_tests/utils.py
> +        raise
What is the aim of this?

2020-10-08 09:23 UTC, Emulebest commented on papiea-sdk/python/papiea/client.py
> +    # filter_intent_watcher(AttributeDict(status='Pending'))
This should be enum like the one in TS

2020-10-08 09:23 UTC, Emulebest commented on papiea-sdk/python/e2e_tests/utils.py
> +async def wait_for_status_change(kind: str, entity_ref: AttributeDict, status: Any, sync: bool, callback: Any = None, retries: int = 10) -> bool:
The concept is similar to Typescript one. Let's firstly move it to `ProviderClient`, then make the signature similar to Typescript one. Instead of `.then()` a user would utilize https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.add_done_callback or push Future to a different thread

2020-10-13 09:06 UTC, Emulebest requested changes
Final set of comments

2020-10-13 09:06 UTC, Emulebest commented on papiea-sdk/python/e2e_tests/sdk_test.py
> +                    await self.add_done_callback(task, cb_function, b1_object1_entity)
I'd change the flow of the test to this
```
invoked_callback = False
def cb_func(fut: Future):
    global invoked_callback
    invoked_callback = True
task = asyncio.create_task(sdk.intent_watcher.wait_for_watcher_status(watcher_ref.watcher, watcher_status, 50))
task.add_done_callback(cb_function)
await asyncio.sleep(5) # Please find the lowest timeout not to slow down the tests
assert(invoked_callback == True)
```

2020-10-13 09:06 UTC, Emulebest commented on papiea-sdk/python/e2e_tests/sdk_test.py
> +        return result
You don't need this, please see the comment below

2020-10-13 19:34 UTC, nitesh-idnani1 commented on papiea-client/src/entity_client.ts
> +async function wait_for_watcher_status(papiea_url: string, s2skey: string, watcher_ref: IntentWatcher, watcher_status: any, limit: number = 50): Promise<boolean> {
Done

2020-10-13 20:32 UTC, nitesh-idnani1 commented on papiea-client/src/entity_client.ts
> +        await delay(5000)
Okay, will change delay to 500ms

2020-10-13 20:32 UTC, nitesh-idnani1 commented on papiea-sdk/python/papiea/client.py
> +    async def wait_for_watcher_status(self, watcher_ref: AttributeDict, watcher_status: AttributeDict, limit: int = 50) -> bool:
Done

2020-10-13 20:33 UTC, nitesh-idnani1 commented on papiea-sdk/python/papiea/client.py
> +                time.sleep(5)
Done

2020-10-15 12:03 UTC, Emulebest approved these changes

2020-10-15 12:03 UTC, merged