Nested value of type any in update_status fix
nutanix/papiea pull request #542
Opened 2020-11-05 21:14 UTC by nitesh-idnani1

Fixed nested value initialization of type any in update_status by adding existence check in fix_null_objects module.

2020-11-05 22:30 UTC, shlomi-nx reviewed
Looks good, minor comment

2020-11-05 22:30 UTC, shlomi-nx commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +            const res: any = await axios.post(`${sdk.entity_url}/${sdk.provider.prefix}/${sdk.provider.version}/${kind_name}/${metadata.uuid}/procedure/testProcedure`, null);
I see this test as well as the next don't take any input parameters. I would keep at least one with input parameters (the schema can be in the source, no need for external file). But its good to test different paths.

2020-11-05 23:02 UTC, nitesh-idnani1 commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +            const res: any = await axios.post(`${sdk.entity_url}/${sdk.provider.prefix}/${sdk.provider.version}/${kind_name}/${metadata.uuid}/procedure/testProcedure`, null);
Changed one test to take an input parameter

2020-11-05 23:36 UTC, shlomi-nx requested changes
Please see comment

2020-11-05 23:36 UTC, shlomi-nx commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +    }
I wouldn't use schemas from bmaas. Please be aware that Papiea is open and everyone could read its contents, while bmaas is closed. Please come up with an example schema which does not leak proprietary information.

2020-11-05 23:48 UTC, nitesh-idnani1 commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +    }
Ohh I'm sorry, I'll change this to a generic one. Thanks for pointing this out.

2020-11-06 09:20 UTC, Emulebest approved these changes

2020-11-09 19:04 UTC, merged