Added module to remove status-only fields from entity status
nutanix/papiea pull request #546
Opened 2020-11-12 00:10 UTC by nitesh-idnani1

Added module to loop through the entity schema and remove all the `status-only` fields from the entity status object.
Added test to verify the functionality

2020-11-12 00:16 UTC, shlomi-nx reviewed
Looks good, please see comment about test below.

2020-11-12 00:16 UTC, shlomi-nx commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +                            }
I'd add another field that is not `status-only`, otherwise you are hitting a base case where outside of the identifier the content is empty. By having `b` which is the same and `a` which is different but status only we can make sure logic works better.

2020-11-12 10:19 UTC, Emulebest requested changes

2020-11-12 10:19 UTC, Emulebest commented on papiea-engine/src/intentful_engine/diff_resolver.ts
> +    private remove_status_only_fields(schema: any, status: Status): Status {
I am not sure this fits here (in diff resolver), I think this kind of cleanup should be done in the `Differ` specific implementation. Some day we might want to have a differ which is aware of schema

2020-11-19 11:30 UTC, Emulebest requested changes
A single remark, other than that good job!

2020-11-19 11:30 UTC, Emulebest commented on papiea-engine/src/intentful_engine/diff_resolver.ts
> +            let diff_status = Object.assign({}, status);
Damn Javascript, one more quirk here. Object.assign() only clones a single level of object depth, so I suggest using `JSON.parse(JSON.stringify(status))` here to clone the whole object

2020-12-03 19:17 UTC, nitesh-idnani1 commented
Hey @Emulebest
Can you review this PR and merge it, thanks.

2020-12-08 19:02 UTC, Emulebest approved these changes

2020-12-08 19:03 UTC, merged