Added semantic version check for the papiea sdk requests
nutanix/papiea pull request #573
Opened 2020-12-17 21:28 UTC by nitesh-idnani1

- Added get version function in the typescript provider sdk class,
- Defined version header to use in the papiea sdk requests.
- Defined a version check middleware in express validator to validate the sdk version.

2020-12-18 12:22 UTC, Emulebest requested changes
@nitesh-idnani1 Please add papiea-client checks, testing (add a mock implementation that gives you a specified version on both ends):
 1. Showcase that this indeed rejects invalid version (total incompatibility e.g. 1.0 vs 0.0.1)
 2. Positive case when versions are matching
 3. Positive case when versions are compatible

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/validator/express_validator.ts
> +    router.use('/provider/', checkSDKVersion);
These are unnecessary. See https://expressjs.com/en/guide/using-middleware.html

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/validator/express_validator.ts
> +    const router = Router();
You don't need a router here

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/validator/express_validator.ts
> +    return router;
I don't think this middleware needs a router at all

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/validator/express_validator.ts
> +        const headersSDKVersion = req.headers['papiea-sdk-version']
I think this should be `papiea-version` since papiea-client version should be also checked

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/validator/express_validator.ts
> +        if (headersSDKVersion && semver.lt(headersSDKVersion, engineSDKVersion)) {
This doesn't check that versions are compatible, it only checks that one is less than another

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/validator/express_validator.ts
> +            throw new BadRequestError(`Expected sdk version to be >= ${engineSDKVersion}, got ${headersSDKVersion}`)
Please check my message above in regards to compatibility not a lt/gt check

2020-12-18 12:22 UTC, Emulebest commented on papiea-engine/src/main.ts
> +    const engineSDKVersion = packageJSON.version.split('+')[0];
Please abstract the details away (maybe move those to util function)

2020-12-18 12:22 UTC, Emulebest commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +                  "Papiea-SDK-Version": sdk.get_sdk_version()
Please check the comment above in regards to this header name

2020-12-18 12:22 UTC, Emulebest commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> +        this._sdk_version = packageJSON.version.split('+')[0];
Please abstract the details away

2020-12-28 23:34 UTC, nitesh-idnani1 commented on papiea-engine/src/validator/express_validator.ts
> +        if (headersSDKVersion && semver.lt(headersSDKVersion, engineSDKVersion)) {
Made some changes. Let me know if we need anything more.

2021-01-04 12:31 UTC, Emulebest approved these changes
Looks good! Well done!

2021-01-04 19:00 UTC, merged