Added authorizer for intent watcher related operations
nutanix/papiea pull request #591
Opened 2021-01-12 04:34 UTC by nitesh-idnani1

- Added intent watcher authorizor implementation for watcher related ops.
- Added tests to verify the authorization for intent watcher related ops.

2021-01-13 11:21 UTC, Emulebest requested changes
Looks good, a few moments to note

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/auth/authz.ts
> +        }
I think all of these errors should be either BadRequest or PermissionDenied (the absent user one definitely) because general errors are confusing

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/diff_resolver_main.ts
> +    const intentfulContext = new IntentfulContext(specDb, statusDb, graveyardDb, differ, intentWatcherDB, watchlistDb, validator, noopAuthorizer, noopAuthorizer)
This one is getting noopAuthorizer twice, typo?

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
> +    constructor(specDb: Spec_DB, statusDb: Status_DB, graveyardDb: Graveyard_DB, differ: Differ, intentWatcherDb: IntentWatcher_DB, watchlistDb: Watchlist_DB, intentWatcherAuthorizer: Authorizer) {
Does this strategy use intentWatcherAuthorizer internally?

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/intentful_core/intentful_strategies/differ_intentful_strategy.ts
> +    protected intentWatcherAuthorizer: Authorizer;
Does this strategy use intentWatcherAuthorizer internally?

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/intentful_core/intentful_context.ts
> +    constructor(specDb: Spec_DB, statusDb: Status_DB, graveyardDb: Graveyard_DB, differ: Differ, intentWatcherDb: IntentWatcher_DB, watchlistDb: Watchlist_DB, validator: Validator, authorizer: Author
Does the context use intentWatcherAuthorizer internally?

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/intentful_core/intentful_context.ts
> +        this.behaviourStrategyMap.set(IntentfulBehaviour.Basic, new DifferIntentfulStrategy(specDb, statusDb, graveyardDb, differ, intentWatcherDb, watchlistDb, intentWatcherAuthorizer))
Does the context use intentWatcherAuthorizer internally?

2021-01-13 11:21 UTC, Emulebest commented on papiea-engine/src/intentful_core/intentful_context.ts
> +        this.behaviourStrategyMap.set(IntentfulBehaviour.Differ, new DifferIntentfulStrategy(specDb, statusDb, graveyardDb, differ, intentWatcherDb, watchlistDb, intentWatcherAuthorizer))
Does the context use intentWatcherAuthorizer internally?

2021-01-13 18:34 UTC, nitesh-idnani1 commented on papiea-engine/src/diff_resolver_main.ts
> +    const intentfulContext = new IntentfulContext(specDb, statusDb, graveyardDb, differ, intentWatcherDB, watchlistDb, validator, noopAuthorizer, noopAuthorizer)
No, it takes 2 authorizers i.e. a PerProvider one and an IntentWatcher one

2021-01-13 18:36 UTC, nitesh-idnani1 commented on papiea-engine/src/diff_resolver_main.ts
> +    const intentfulContext = new IntentfulContext(specDb, statusDb, graveyardDb, differ, intentWatcherDB, watchlistDb, validator, noopAuthorizer, noopAuthorizer)
Yeah, I missed that. I'll remove the intentwatcher authorizer parameter here

2021-01-14 18:05 UTC, Emulebest requested changes
A few super minor comments and you could merge this in

2021-01-14 18:05 UTC, Emulebest commented on papiea-engine/src/entity/entity_api_impl.ts
>          // TODO: this should be a separate authorizer not a PerProvider one
Remove this comment please

2021-01-14 18:05 UTC, Emulebest commented on papiea-engine/src/auth/authz.ts
> +            throw new BadRequestError("No provider provided in the authorizer")
It more of `Couldn't find a provider for the entity`

2021-01-14 18:05 UTC, Emulebest commented on papiea-engine/src/entity/entity_api_impl.ts
>          // TODO: this should be a separate authorizer not a PerProvider one
Remove this comment please

2021-01-18 12:02 UTC, Emulebest approved these changes

2021-01-18 12:02 UTC, merged