Removed requirement for input field in the procedures input.
nutanix/papiea pull request #592
Opened 2021-01-13 08:35 UTC by nitesh-idnani1

- Removed requirement for input field in procedure's input.
- Modified and fixed tests to use the new input schema changes for procedure calls.

2021-01-18 12:03 UTC, Emulebest commented
Is this one ready? If not please link why and maybe convert to draft

2021-01-20 18:30 UTC, nitesh-idnani1 commented
> Is this one ready? If not please link why and maybe convert to draft

Yes, converting this to in progress and will be completed once we finalize the idea mentioned in the input schema discussion.
#593

2021-01-25 15:08 UTC, Emulebest requested changes

2021-01-25 15:08 UTC, Emulebest commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe("Unable to validate an empty value for property: rootModel")
This error message signifies that something has gone off the roads here :). This is one of our most popular bugs `Unable to validate an empty value for property: rootModel` and should be addressed for this particular case (empty input)

2021-01-25 18:00 UTC, nitesh-idnani1 commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe("Unable to validate an empty value for property: rootModel")
So, we should be throwing a specific error message for the empty input case rather than the above one, is that what you mean?

2021-01-25 18:01 UTC, Emulebest commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe("Unable to validate an empty value for property: rootModel")
Correct

2021-01-25 18:03 UTC, nitesh-idnani1 commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe("Unable to validate an empty value for property: rootModel")
Okay, I'll look into it. Thanks

2021-01-25 22:12 UTC, nitesh-idnani1 commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe("Unable to validate an empty value for property: rootModel")
Added check in the validate function to throw error if model is not nullable (i.e. has required fields) and the input is empty/null. Kindly check and let me know if we need anything else. Thanks

2021-01-28 20:10 UTC, nitesh-idnani1 commented
Reverted the new commit since I and @joshua-berry-ntnx has a discussion and decided it would be a bad practice to specify non-json or non-object like input to the procedures.

@shlomi-nx
Feel free to add your thoughts to this. Thanks

2021-02-02 22:03 UTC, nitesh-idnani1 commented
This PR has the changes discussed today. Kindly review and merge it. Thanks

2021-02-04 16:02 UTC, Emulebest commented
@nitesh-idnani1 Regarding the recent bugs, could you also merge master into this branch and manually verify that api-docs are correctly rendered

2021-02-04 19:06 UTC, merged