Reduced diff retry backoff exponent for debugging purposes
nutanix/papiea pull request #594
Opened 2021-01-19 21:09 UTC by nitesh-idnani1

- Added papiea debug variable in diff resolver to use in diff retry logic.
- Reduced retry backoff exponent to `1.3` if debug flag is set in engine.
- Modified tests to adjust to the above changes.

2021-01-20 01:02 UTC, joshua-berry-ntnx commented
I don't think we should do this just in debug builds, I think it's quite relevant for release builds as well.

2021-01-20 01:26 UTC, nitesh-idnani1 commented
> I don't think we should do this just in debug builds, I think it's quite relevant for release builds as well.

Yes, I am thinking about two things i.e.
1. What would be an ideal value for this considering the latency and workflows for papiea, maybe @Emulebest can provide more inputs on this?
2. If (and how) we should allow the user to customize the value for the backoff exponent?

2021-01-25 14:58 UTC, Emulebest requested changes
I don't like passing debug variable to the business logic, please take a look at the example in the comments

2021-01-25 14:58 UTC, Emulebest commented on papiea-engine/src/intentful_engine/diff_resolver.ts
> +    private createDiffBackoff(kind: Kind, delay: Delay | null | undefined, papieaDebug: boolean, retries: number = 0): Backoff {
This is too intrusive IMO, please take a look at my approach here https://github.com/nutanix/papiea/blob/e531a23927b9e66d4b7d93f05a824d9774332e57/papiea-engine/src/diff_resolver_main.ts#L49

2021-01-25 15:01 UTC, Emulebest commented
> > I don't think we should do this just in debug builds, I think it's quite relevant for release builds as well.
> 
> Yes, I am thinking about two things i.e.
> 
> 1. What would be an ideal value for this considering the latency and workflows for papiea, maybe @Emulebest can provide more inputs on this?
> 2. If (and how) we should allow the user to customize the value for the backoff exponent?

I'd rather let a user judge on the matters of the idea constant.

Anyhow, we could add it to one of our config variables like used here:
https://github.com/nutanix/papiea/blob/master/papiea-engine/papiea-config.yaml

https://github.com/nutanix/papiea/blob/master/papiea-engine/src/utils/arg_parser.ts

2021-01-25 20:17 UTC, nitesh-idnani1 commented
> > > I don't think we should do this just in debug builds, I think it's quite relevant for release builds as well.
> > 
> > 
> > Yes, I am thinking about two things i.e.
> > 
> > 1. What would be an ideal value for this considering the latency and workflows for papiea, maybe @Emulebest can provide more inputs on this?
> > 2. If (and how) we should allow the user to customize the value for the backoff exponent?
> 
> I'd rather let a user judge on the matters of the idea constant.
> 
> Anyhow, we could add it to one of our config variables like it is used here:
> https://github.com/nutanix/papiea/blob/master/papiea-engine/papiea-config.yaml
> 
> https://github.com/nutanix/papiea/blob/master/papiea-engine/src/utils/arg_parser.ts

Added a config variable for the diff retry exponent value. Kindly check and review the changes. Thanks

2021-02-01 10:30 UTC, Emulebest requested changes
One general caveat in the code. @shlomi-nx @joshua-berry-ntnx please take a look at the comment in the PR, any ideas?

2021-02-01 10:30 UTC, Emulebest commented on papiea-engine/src/utils/utils.ts
> +        console.log("Debug flag is set. Setting the diff retry exponent to 1.3")
Console.log is not a proper logging, please adjust to use the logger

2021-02-01 10:30 UTC, Emulebest commented on papiea-engine/src/utils/utils.ts
> +    }
I second @joshua-berry-ntnx opinion, let's have it tunable. Moreover, this gets me to think whether we should maybe do the debug config instead of debug flags for such cases, @shlomi-nx @joshua-berry-ntnx what do you think?

2021-02-01 18:36 UTC, shlomi-nx commented
I too agree with hiding things behind `debug` flag is not good. But I think more generally, retry frequency should be related to the provider itself, not the engine. Some providers would need more rapid retries, while others not. 

We already have a per-handler retry mechanism, specified by the return value of the handler. Perhaps we could unblock ourselves there, while per-provider retry configuration is being worked on?

2021-02-02 19:32 UTC, nitesh-idnani1 commented
Review and merge this PR, and I will start working on the discussed enhancement to add the diff retry in the kind registration. Thanks

2021-02-02 20:34 UTC, shlomi-nx requested changes
I would still like to not use the general purpose `debug` flag. Lets replace it with `papiea_retry_exponent` to signal that this is a papiea-wide retry exponent. Later we could add provider/kind specific configuration as discussed.

2021-02-02 23:23 UTC, nitesh-idnani1 commented
I'm ready with the new changes that we discussed i.e. allow user to specify kind-level diff retry exponent value. The changes are not big and compatible with this PR changes.
Let me know if I can add them here or create a separate PR for the new changes.

2021-02-03 00:36 UTC, shlomi-nx reviewed
Looks good. Sure you can add the kind exponent configuration to this PR.

2021-02-03 00:36 UTC, shlomi-nx commented on papiea-engine/src/utils/utils.ts
> +    return (retries?: number, maximumBackoff?: number, entropy?: number) => {
I like curry ;)

2021-02-03 01:19 UTC, shlomi-nx requested changes
Looks good, but I rather not change the kind signature.

2021-02-03 01:19 UTC, shlomi-nx commented on papiea-engine/src/utils/utils.ts
> +        return 10
What is this 10 number?

2021-02-03 01:19 UTC, shlomi-nx commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> +    new_kind(entity_description: Data_Description, diff_retry_exponent?: number): Kind_Builder {
Let's add this configuration as a function. 

```
const k = new kind(schema)
k.setExponentBackoff(1.2)
```

If we do want to keep it in the schema, we could add something like `x-papiea-backoff-exponent` tag that is allowed on a kind entity.

2021-02-03 01:58 UTC, nitesh-idnani1 commented on papiea-engine/src/utils/utils.ts
> +        return 10
Added this for safety. If one of the param is null/undefined, set the backoff delay to 10 sec.

2021-02-03 02:00 UTC, nitesh-idnani1 commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> +    new_kind(entity_description: Data_Description, diff_retry_exponent?: number): Kind_Builder {
Changing this to a function for now, we can change this later based on the requirements.

2021-02-03 02:28 UTC, shlomi-nx commented on papiea-engine/src/utils/utils.ts
> +        return 10
oh I see. Let's add a loud WARNING message there, to know that we are using unexpected defaults, and the reason we must have reached there.

2021-02-03 18:52 UTC, shlomi-nx approved these changes
Looks good to me

2021-02-04 07:26 UTC, merged