Entity API tests for the papiea client in typescript sdk
nutanix/papiea pull request #597
Opened 2021-01-27 23:36 UTC by nitesh-idnani1

- Added success test cases for the entity client API operations

2021-02-02 10:01 UTC, Emulebest reviewed
To be honest, I'd rather we make a simple scenario for this, rather than copying the functionality of engine tests. Otherwise, we would need to implement the same case for other client as well. 

Also is yarn-error.log file needed in the PR?

2021-02-02 17:45 UTC, nitesh-idnani1 commented
> To be honest, I'd rather we make a simple scenario for this, rather than copying the functionality of engine tests. Otherwise, we would need to implement the same case for other client as well.
> 
> Also is yarn-error.log file needed in the PR?

Yes, I'm working on the next steps for this which will include a e2e test scenario similar to what we have in python e2e tests. We can discuss more on this is the meeting.
Also, removed the yarn-error log file, it was added by mistake.

2021-02-18 19:05 UTC, shlomi-nx reviewed
Looks very good to me. A couple of minor comments.

Perhaps we should extract this e2e provider as an example provider, and have the e2e use it. This way we can add this as a canonical example for papiea, and have the Readme point to it.

2021-02-18 19:05 UTC, shlomi-nx commented on papiea-sdk/typescript/__tests__/client_tests/e2e_tests/test_setup.ts
> +    utils.get_kind_ref_type(config.bucket, "Reference of the bucket in which the object exists")
Suggestion: Although convenient to use here, perhaps one of these should remain in the yaml to serve as a dual example - how to do that directly in YAML, and the benefits of doing through code

2021-02-18 19:18 UTC, nitesh-idnani1 commented on papiea-client/src/entity_client.ts
> +    const res = await make_request(axios.post, `${ papiea_url }/services/${ provider }/${ version }/${ kind }/filter${ query_val }`, filter, {headers});
The query was already a part of the papiea engine implementation, but there was no support to set it through the client.
These are the permissible query params supported now
https://github.com/nutanix/papiea/blob/c8f8e3b6fc8a03301aa13ba073373a3ca6d522a1/papiea-engine/src/entity/entity_routes.ts#L135

2021-02-19 11:25 UTC, Emulebest requested changes
One small change. I think it is better to have directory structure of:
`__tests__`
      `provider_sdk_tests`
      `intentful_workflow_tests`
      `e2e_tests`

Other than that feel free to merge

2021-02-19 19:53 UTC, merged