Improved logging information for papiea
nutanix/papiea pull request #623
Opened 2021-02-11 08:02 UTC by nitesh-idnani1

- Added request URL field in papiea error responses.
- Added relevant information in the error messages.
- Added helper module to transform validator library messages to relevant papiea messages.
- Added relevant information in the logger messages.
- Modified tests to verify the new logging changes.

Closes #575, #577, #600, #619

2021-02-11 20:25 UTC, shlomi-nx requested changes
Reviewed most files but not all changes.

Please see my comments below, I still see some context missing, and added suggestions for improved log format. Also please be sure we do not swallow stack traces.

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-client/src/entity_client.ts
> +            throw new Error("Timeout waiting for intent watcher status change")
Timeout on which entity? provider? kind? version? :)

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/__tests__/entity_tests/extension.test.ts
> +            expect(res.data.error.errors[0].message).toContain('Metadata extension: \"\" should be an object for entity')
`for entity` conveys no useful information. Kind, provider, version do.

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/__tests__/entity_tests/pagination.test.ts
> +            expect(e.response.data.error.errors[0].message).toBe("Offset should be greater than zero, received: 0");
I think not allowing offset of 0 is little too rigid. Offset of 0 is the same as no offset.

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/__tests__/entity_tests/uuid_validation.test.ts
> +            expect(e.response.data.error.message).toContain("Metadata uuid is undefined but validation pattern is specified for entity with kind")
Perhaps show the validation patten here. as well as kind, provider, version

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe("Procedure: moveX with schema: MoveInput was expecting non-empty input");
In which kind, provider, version?

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toContain("Input is missing required field: x");
For which procedure, on which kind, provider, version?

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/auth/oauth2.ts
> +            logger.error(`Failed to logout user with token: ${token} due to error: ${e.message}`);
On which provider? version?

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/auth/authz.ts
> +                throw new PermissionDeniedError(`User has wrong provider prefix for the object with prefix: ${object.provider_prefix} in admin permission check to read/inactivate s2skey`);
Don't have to mention `prefix` in the message. Provider prefix is just the provider name..

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/auth/session_key.ts
> +            throw new Error(`Couldn't refresh the session token: ${e.message}`)
Session for which provider? which idp url? maybe which user?

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/databases/graveyard_db_mongo.ts
> +            throw new Error(`MongoDBError: Failed to remove entity with uuid: ${entity_ref.uuid}, kind: ${entity_ref.kind}, provider_prefix: ${entity_ref.provider_prefix}, provider_version: ${entity_
You could simply write `... provider: ${entity_ref.provider_prefix}/${entity_ref.provider_version} ..` when you want to log the provider information. This way it will look like `blah blah on provider shlomi/1.0.1`. 

This holds for all the logs, makes it easier to read

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/databases/intent_watcher_db_mongo.ts
> +            throw new EntityNotFoundError('IntentWatcher', uuid);
IntentWatcher uuids are nice, but I would like an explicit print of the provider/version/kind and even entity uuid in  logs that have intentwatcher in them.

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/intentful_core/intentful_context.ts
> +            throw new Error(`Strategy associated with behaviour: ${kind.intentful_behaviour} not found for kind: ${kind.name}`)
on `provider/version`

2021-02-11 20:25 UTC, shlomi-nx commented on papiea-engine/src/intentful_engine/diff_resolver.ts
> +            this.logger.debug(`Couldn't generate diff for entity with uuid: ${entry_reference.entity_reference.uuid} and kind: ${entry_reference.entity_reference.kind} due to error: ${e}. Removing fr
`Couldn't generate diff for entity {uuid} on {provider}/{version}/{kind} due to ${e} ...` 

Also, note that `${e}` does not print the stack trace, so we are swallowing the stack trace here, which is very unfortunate.

2021-02-12 12:14 UTC, Emulebest requested changes
I second Shlomi's review. I'd suggest extending or changing PapieaError's constructor for it to optionally include all the provider and entity info to extract

2021-02-12 18:36 UTC, shlomi-nx commented
+1 on @Ntnx-Igor-Korotach's idea, if we formalize the entity information for exceptions and logs we could achieve two things:
1. Uniformity - all logs will have the same info without the need to remember manually to write them
2. Searchability - If these would get logged as json entries, we could later filter logs of particular entities/providers etc.

2021-02-16 11:19 UTC, Emulebest requested changes

2021-02-16 11:19 UTC, Emulebest commented on papiea-backend-utils/src/index.ts
> +export class EntityLoggingInfo {
This class doesn't solve the problem of uniformity @shlomi-nx and I raised since you essentially need to remember to pass it as a second parameter. This is good as an aggregator class but what you actually need is a strict error interface that requires something like this in the constructor (possibly using this class). 

Also `setAdditionalField` is a good fit for Java but there is no need to pollute the environment with these calls if you can pass an `any` type parameter in the constructor of factory function.

`toString` should be called internally from the single entry point (for reference you can use https://github.com/nutanix/papiea/blob/78435c935e6b5f5d021ac46ec0193d8611ba5703/papiea-engine/src/main.ts#L95)

2021-02-16 17:43 UTC, nitesh-idnani1 commented on papiea-backend-utils/src/index.ts
> +export class EntityLoggingInfo {
Having it in the constructor would still require us to initialize it every time we throw an error right?

The idea behind `setAdditionalField` is to simplify the logging interface (similar to the sdk interface).

I'll work on the toString part and add in the papiea error implementation. Thanks for pointing that out.

2021-02-17 12:10 UTC, Emulebest requested changes
Looks better but please see the comments :)

2021-02-17 12:10 UTC, Emulebest commented on papiea-engine/src/databases/utils/errors.ts
>  }
This is a good place to highlight what should be changed.

In the comments above I spoke about `PapieaError` being implemented. These are my thought on how that should be done:

1) Make `PapieaError` (or better `PapieaException` to not collide with the existing naming) inherit `Error`
2) `PapieaException` should have a constructor that has an `exception_context` essential argument that features all the possible options (`prefix`, `version`, `kind`) as optional properties (this should be typed out as `PapieaExceptionContext`)
3) Use `EntityLoggingInfo` internally to aggregate those as good error strings
4) Override the `toString` function for generic view of error context

Then working with classes like `EntityNotFoundError`:

1) Inherit from `PapieaException`
2) Have signature feature essential param needed in the super class constructor
e.g.
```
constructor(kind: string, uuid: uuid4, exception_context: PapieaExceptionContext)
```
3) Override `toString` to add up messages on top of `PapieaException`'s `toString`
4) Change https://github.com/nutanix/papiea/blob/78435c935e6b5f5d021ac46ec0193d8611ba5703/papiea-engine/src/errors/papiea_error_impl.ts#L63 to use errors' `toString` instead of `err.message`

2021-02-17 12:10 UTC, Emulebest commented on papiea-engine/src/entity/entity_api_impl.ts
> +                throw new PermissionDeniedError(`User does not have permission on entity`, entityRef.provider_prefix, entityRef.provider_version, entityRef.kind, additional_info)
In place additional info when properly formatted is better for readability

2021-02-18 10:00 UTC, Emulebest reviewed
Looks good! @nitesh-idnani1 is this completely ready or you are still working on it?

2021-02-18 10:00 UTC, Emulebest commented on papiea-engine/src/errors/validation_error.ts
> +        });
Does this include formatted messages from `PapieaException` base class?

2021-02-18 17:45 UTC, nitesh-idnani1 commented on papiea-engine/src/errors/validation_error.ts
> +        });
No, since the papiea base class contains only the exception context I've separated its usage in papiea error impl like this
https://github.com/nutanix/papiea/blob/934c69fcb68d67165228b4b2aae8c3bce3b8d255/papiea-engine/src/errors/papiea_error_impl.ts#L33

2021-02-18 19:54 UTC, shlomi-nx reviewed
Reviewed partially, that's a loooong PR! :)

I added a bunch of improved error texts. I later saw that errors contain structured fields, but I thought that having a meaningful string can be helpful when trying to read the log. 

Let me know what you think about my proposals and lets try to get this merged asap. This looks very good, and will be a wonderful improvement for our users!

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-client/src/entity_client.ts
> +            throw new Error(`Timeout waiting for intent watcher status change with uuid: ${watcher.uuid} and entity uuid: ${watcher.entity_ref.uuid}`)
provider/version/kind

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/__tests__/entity_tests/uuid_validation.test.ts
> +            expect(e.response.data.error.errors[0].message).toBe(`Metadata uuid is undefined but kind has validation pattern set`)
provider/version/kind. Let's also show the pattern. 
Perhaps its useful to also add the context of the call, something like 
```
Creating a new entity of {provider/version/kind} failed. Metadata uuid received is undefined but the kind has the following unsatisfied validation pattern {pattern}
```

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/src/intentful_core/sfs_compiler.ts
> +                new PapieaException(`SFS parsing on kind failed with error: ${e.message}`, { kind_name: kind_name, additional_info: { "signature": signature }})
Please add kind coordinates {provider/version/kind}. Perhaps rename `signature` to SFS, to be consistent with the message. 

Also notice that the stacktrace is swallowed, lets find a way to always aggregate stacktraces, never drop them.

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toBe(`Procedure was expecting non-empty object`);
Kind coordinates are missing from the error message. Also some context:
```
Could not invoke procedure {provider/version/kind/procedure}. Procedure definition expects a non-empty object, but an empty object was provided.
```

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            expect(res.data.error.errors[0].message).toContain(`Input is missing required field: x`);
I may be missing the full message, but I think it should be something like:

```
Could not invoke procedure {provider/version/kind/procedure}. Received procedure arguments is missing a required field {x}.
```

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +            expect(e.response.data.error.errors[0].message).toBe("x-papiea has wrong value: spec-only, correct values include: status-only");
```
Cannot register {provider}/{version}. Kind {kind} has invalid definition: x-papiea has wrong value: spec-only, correct values are: status-only
```

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/__tests__/provider_tests/provider_api.test.ts
> +            expect(e.response.data.error.errors[0].message).toEqual(`Status body is undefined for entity, please use null fields instead`)
```
Cannot update status for {provider/version/kind}. Status body contains undefined fields which Papiea does not support. If you are trying to remove a field from status it should be set to null value instead.
```

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/src/auth/casbin.ts
> +                throw new PermissionDeniedError(`User does not have permission for the entity`, { additional_info: { "user": JSON.stringify(user), "action": action, "entity": JSON.stringify(object) }
Missing provider/version

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/src/auth/oauth2.ts
> +            logger.error(`Failed to logout user with token: ${token} in provider with prefix: ${provider.prefix} and version: ${provider.version} due to error: ${e.message}`);
Can we condense the provider/prefix to simply that? 

```
Failed to logout user with token: ${token} for ${provider.prefix}/${provider.version} due to error: ${e.message}
```

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/src/databases/intent_watcher_db_mongo.ts
> +            throw new EntityNotFoundError('IntentWatcher', uuid);
This is resolved, but I am not seeing the comment addressed here.. Am I missing something?

2021-02-18 19:54 UTC, shlomi-nx commented on papiea-engine/src/entity/entity_api_impl.ts
> +            throw new PapieaException(`Entity procedure not found`, { provider_prefix: prefix, provider_version: version, kind_name: kind.name, additional_info: { "procedure_name": procedure_name }})
I see now that perhaps some of the comments I added above about missing information actually have the info supplied in the structured fields and additional_info. However, maybe it's worthwhile to still keep a nice, readable string along with the structure. Here for example I would write:

```
Entity procedure {procedure_name} not found on {provider/version/kind}.
```

2021-02-18 20:03 UTC, nitesh-idnani1 commented on papiea-engine/__tests__/entity_tests/uuid_validation.test.ts
> +            expect(e.response.data.error.errors[0].message).toBe(`Metadata uuid is undefined but kind has validation pattern set`)
Yes, that info is added in the error context when we throw this error on the engine side

2021-02-18 20:10 UTC, nitesh-idnani1 commented on papiea-engine/src/intentful_core/sfs_compiler.ts
> +                new PapieaException(`SFS parsing on kind failed with error: ${e.message}`, { kind_name: kind_name, additional_info: { "signature": signature }})
@Emulebest 
We should discuss how to retain the stack trace for the errors. I think it'll involve changes in our error implementations.

2021-02-18 20:56 UTC, nitesh-idnani1 commented on papiea-engine/src/databases/intent_watcher_db_mongo.ts
> +            throw new EntityNotFoundError('IntentWatcher', uuid);
Yes, I believe intent watchers do not have the provider related information in their context since they are not associated with one. The only way to add provider information is to fetch intent watcher and use its entity referenced provider info.

Here, since we're not able to fetch the watcher itself there's no way to associate the entity error with a particular provider. However, I've added provider context at other places where we have a valid intent watcher.

2021-02-18 22:43 UTC, nitesh-idnani1 commented on papiea-engine/src/entity/entity_api_impl.ts
> +            throw new PapieaException(`Entity procedure not found`, { provider_prefix: prefix, provider_version: version, kind_name: kind.name, additional_info: { "procedure_name": procedure_name }})
I tried that earlier but I think it's better for readability and debugging purposes to have a clear concise error message separated from the context (entity-related) information.
It can help the end user to get a clear understanding of what went wrong and with which entity did it happen, rather than having all the information cluttered together (quite a few of the papiea messages are already long enough for that).

2021-02-19 11:37 UTC, Emulebest commented on papiea-engine/src/entity/entity_api_impl.ts
> +            throw new PapieaException(`Entity procedure not found`, { provider_prefix: prefix, provider_version: version, kind_name: kind.name, additional_info: { "procedure_name": procedure_name }})
Agree with Nitesh, moreover it is important to get the context of the message to the user. Good looking error string becomes a burden and code mess, not even touching the point of needing for some reason to change the format of `on {provider/version/kind}`. Additionally, some places don't feature one of the components (no kind for example) which makes it a bit hard to keep consistent string

2021-02-19 11:45 UTC, Emulebest commented on papiea-engine/src/intentful_core/sfs_compiler.ts
> +                new PapieaException(`SFS parsing on kind failed with error: ${e.message}`, { kind_name: kind_name, additional_info: { "signature": signature }})
The error stacktraces are stored in `error.stack`. One possible solution is keeping a tree-like structure of error references so that in the `PapieaErrorResponseImpl` we can traverse, aggregate and log the stacktraces. This could be achieve by providing optional 3rd or 2nd argument where error nesting is due or by traversing the array of nested errors in case of `ValidationError`

2021-02-19 11:47 UTC, Emulebest commented on papiea-engine/src/errors/validation_error.ts
> +        });
Sure, well enough

2021-02-19 19:46 UTC, nitesh-idnani1 commented on papiea-engine/src/intentful_core/sfs_compiler.ts
> +                new PapieaException(`SFS parsing on kind failed with error: ${e.message}`, { kind_name: kind_name, additional_info: { "signature": signature }})
I don't see the stack trace getting swallowed in cases of nested errors. I tried to print the stack trace for the above statement and got the following in the logs:
```
papiea-engine    | Error: ["SFS parsing on kind failed with error: Parse error at line 1, column 6:\nwrong, wrong2\n     ^\nExpected:\n\".\"\n\n"]
papiea-engine    |     at Function.try_parse_sfs (/code/papiea-engine/src/intentful_core/sfs_compiler.ts:21:19)
papiea-engine    |     at /code/papiea-engine/src/validator/index.ts:194:70
papiea-engine    |     at Array.forEach (<anonymous>)
papiea-engine    |     at ValidatorImpl.validate_sfs (/code/papiea-engine/src/validator/index.ts:194:43)
papiea-engine    |     at Provider_API_Impl.register_provider (/code/papiea-engine/src/provider/provider_api_impl.ts:48:24)
papiea-engine    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
papiea-engine    |     at /code/papiea-engine/src/provider/provider_routes.ts:11:24
```
Maybe we can add some field in the `PapieaErrorResponseImpl` to ensure we get a valid stack trace for all the error types

2021-02-19 20:27 UTC, shlomi-nx commented on papiea-engine/src/entity/entity_api_impl.ts
> +            throw new PapieaException(`Entity procedure not found`, { provider_prefix: prefix, provider_version: version, kind_name: kind.name, additional_info: { "procedure_name": procedure_name }})
I meant to have both an easily readable string where the information is available, and the structured error information.

2021-02-19 23:25 UTC, merged