Fix error details swallowing in papiea
nutanix/papiea pull request #636
Opened 2021-02-23 19:39 UTC by nitesh-idnani1

Closes #633

2021-02-26 20:53 UTC, nitesh-idnani1 commented
I'm facing some issues with adding special characters like "\n" or "\t" in JSON strings, they are getting parsed as raw characters on the user end and making the error messages look a bit messy. Any idea on how to fix this?
Example:
https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/src/errors/papiea_exception.ts#L15

2021-02-26 21:12 UTC, nitesh-idnani1 commented
As evident this is a large PR with changes in a lot of files, if you want to review the major changes related to design you can look at the following files:
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-core/src/core.ts
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-engine/src/databases/utils/errors.ts
https://github.com/nutanix/papiea/tree/nitesh/fix-error-details-swallowing/papiea-engine/src/errors
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-engine/src/utils/utils.ts
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-sdk/python/papiea/python_sdk.py
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-sdk/python/papiea/python_sdk_exceptions.py
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
https://github.com/nutanix/papiea/blob/nitesh/fix-error-details-swallowing/papiea-sdk/typescript/src/provider_sdk/typescript_sdk_exceptions.ts

All the other files include tests modifications/throw statements modification.

2021-03-03 11:46 UTC, Emulebest requested changes
Overall the PR looks really good. (Note the `for kind:` change request). One thing I am concerned about is how do we handle multiple errors and/or nested errors. Please create a test that:
1) Tries to create a kind with 2 or more incorrect schema parts
2) Catch both errors in the engine via validator
3) Propagate and check both error messages in a single papiea-engine error response

2021-03-03 11:46 UTC, Emulebest commented on papiea-client/src/errors/errors.ts
> +    original_error: any
Why is this type `any`?

2021-03-03 11:46 UTC, Emulebest commented on papiea-client/src/errors/errors.ts
> +        this.name = PapieaError.PapieaException
I think this is more of a `this.type` than name

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/__tests__/database_tests/database_mongo.test.ts
> +            expect(err.entity_info.additional_info.existing_spec_version).toEqual("1");
Why is this now `toEqual("1")` rather than `toEqual(2)`. Seems like a bug that leads to this test being broken

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/__tests__/entity_tests/entity_api.test.ts
> +            expect(e.response.data.error.error_details.message).toEqual(`Deleted entity with UUID ${id} of kind: ${providerPrefix}/${providerVersion}/${kind_name} already exists with this spec versio
Could we substitute the `of kind:` with `of: `. Applies to all of the below

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/src/entity/entity_routes.ts
> +            throw new BadRequestError({ message: `Query parameter: ${fieldName} has invalid type: ${typeof q}, expected (string, undefined).` });
Expected undefined?

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/src/errors/papiea_error_impl.ts
>  export class PapieaErrorResponseImpl implements PapieaResponse {
I think at this point this could be called `PapieaErrorResponseProcessor`

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/src/intentful_core/intentful_strategies/intentful_strategy_interface.ts
> +            throw new OnActionError({ message: `Could not delete the entity since kind: ${entity.metadata?.provider_prefix}/${entity.metadata?.provider_version}/${entity.metadata?.kind} is not regist
since kind?

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/src/utils/utils.ts
> +export function convertEntityInfoToExceptionContext(entity_info: any): PapieaExceptionContext {
Can we move this to be a static method of `PapieaErrorResponseImpl`?

2021-03-03 11:46 UTC, Emulebest commented on papiea-engine/src/utils/utils.ts
> +export function convertAxiosErrorToEngineError(error: any): Error {
Can we move this to be a static method of `PapieaErrorResponseImpl`?

2021-03-03 23:34 UTC, nitesh-idnani1 commented
> Overall the PR looks really good. (Note the `for kind:` change request). One thing I am concerned about is how do we handle multiple errors and/or nested errors. Please create a test that:
> 
> 1. Tries to create a kind with 2 or more incorrect schema parts
> 2. Catch both errors in the engine via validator
> 3. Propagate and check both error messages in a single papiea-engine error response

Already added assert checks for nested and multiple errors:
Nested error - https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts#L2350
Multiple error - https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/__tests__/procedure_tests/procedures_api.test.ts#L156

2021-03-03 23:46 UTC, nitesh-idnani1 commented on papiea-client/src/errors/errors.ts
> +        this.name = PapieaError.PapieaException
Yeah agreed, I'm just re-using the type field extended by the Javascript Error class and taken care to print it as type whenever we include it in the response.
Reference: https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/src/errors/papiea_exception.ts#L33
https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/src/errors/papiea_error_impl.ts#L80

2021-03-03 23:56 UTC, nitesh-idnani1 commented on papiea-engine/__tests__/entity_tests/entity_api.test.ts
> +            expect(e.response.data.error.error_details.message).toEqual(`Deleted entity with UUID ${id} of kind: ${providerPrefix}/${providerVersion}/${kind_name} already exists with this spec versio
Added that to clarify what we're printing, since we have just provider information as some places and kind information at others.

2021-03-04 00:11 UTC, nitesh-idnani1 commented on papiea-engine/src/utils/utils.ts
> +export function convertAxiosErrorToEngineError(error: any): Error {
This method is being used by the Procedure Invocation error to process the axios error and convert it to a suitable Error object. Since, the Procedure Invocation error does not have any context of the error response I decided to make this and "convertEntityInfoToExceptionContext" as util helpers.
Usage Reference:
https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/src/errors/procedure_invocation_error.ts#L24

2021-03-04 12:07 UTC, Emulebest commented on papiea-engine/src/utils/utils.ts
> +export function convertAxiosErrorToEngineError(error: any): Error {
Still I don't see a reason for this to become `PapieaErrorResponseImpl.convertAxiosErrorToEngineError(err.response?.data.error)`. This function is too specific to be a global util IMO

2021-03-04 12:08 UTC, Emulebest commented
> papiea/papiea-engine/__tests__/procedure_tests/procedures_api.test.ts

It seems like it is spliced into one single string, I don't like that. Let's go over that on the call

2021-03-04 12:09 UTC, Emulebest commented
> > Overall the PR looks really good. (Note the `for kind:` change request). One thing I am concerned about is how do we handle multiple errors and/or nested errors. Please create a test that:
> > 
> > 1. Tries to create a kind with 2 or more incorrect schema parts
> > 2. Catch both errors in the engine via validator
> > 3. Propagate and check both error messages in a single papiea-engine error response
> 
> Already added assert checks for nested and multiple errors:
> Nested error -
> 
> https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts#L2350
> 
> 
> Multiple error -
> https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/__tests__/procedure_tests/procedures_api.test.ts#L156

It seems like it is spliced into one single string, I don't like that. Let's go over that on the call

2021-03-05 21:31 UTC, nitesh-idnani1 commented
Analyzed the requirements for validation error type, there is only one module wherein we throw multiple errors within the validation error "cause".
So in order to avoid complicating the error design, I modified the validator module to generate multiple error in an list format which the user can parse (JSON.parse) and then go through each error message as an individual item.
Also, I realized the stack trace for each error type is not that relevant since the ValidationError already encapsulates the trace upto the error cause, and since we hide the trace from user I felt it's too much redundancy to keep trace for each individual error.

2021-03-05 21:32 UTC, nitesh-idnani1 commented
> > > Overall the PR looks really good. (Note the `for kind:` change request). One thing I am concerned about is how do we handle multiple errors and/or nested errors. Please create a test that:
> > > 
> > > 1. Tries to create a kind with 2 or more incorrect schema parts
> > > 2. Catch both errors in the engine via validator
> > > 3. Propagate and check both error messages in a single papiea-engine error response
> > 
> > 
> > Already added assert checks for nested and multiple errors:
> > Nested error -
> > https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts#L2350
> > 
> > Multiple error -
> > https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/__tests__/procedure_tests/procedures_api.test.ts#L156
> 
> It seems like it is spliced into one single string, I don't like that. Let's go over that on the call

Analyzed the requirements for validation error type, there is only one module wherein we throw multiple errors within the validation error "cause".
So in order to avoid complicating the error design, I modified the validator module to generate multiple error in an list format which the user can parse (JSON.parse) and then go through each error message as an individual item.
Also, I realized the stack trace for each error type is not that relevant since the ValidationError already encapsulates the trace upto the error cause, and since we hide the trace from user I felt it's too much redundancy to keep trace for each individual error.

2021-03-11 11:20 UTC, Emulebest commented
> > > > Overall the PR looks really good. (Note the `for kind:` change request). One thing I am concerned about is how do we handle multiple errors and/or nested errors. Please create a test that:
> > > > 
> > > > 1. Tries to create a kind with 2 or more incorrect schema parts
> > > > 2. Catch both errors in the engine via validator
> > > > 3. Propagate and check both error messages in a single papiea-engine error response
> > > 
> > > 
> > > Already added assert checks for nested and multiple errors:
> > > Nested error -
> > > https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts#L2350
> > > 
> > > Multiple error -
> > > https://github.com/nutanix/papiea/blob/061403b097330fb5a814111c46f92d2d403f6a10/papiea-engine/__tests__/procedure_tests/procedures_api.test.ts#L156
> > 
> > 
> > It seems like it is spliced into one single string, I don't like that. Let's go over that on the call
> 
> Analyzed the requirements for validation error type, there is only one module wherein we throw multiple errors within the validation error "cause".
> So in order to avoid complicating the error design, I modified the validator module to generate multiple error in an list format which the user can parse (JSON.parse) and then go through each error message as an individual item.
> Also, I realized the stack trace for each error type is not that relevant since the ValidationError already encapsulates the trace upto the error cause, and since we hide the trace from user I felt it's too much redundancy to keep trace for each individual error.

If the error design has some cases that requires complication then let's do this. Asking users to sometimes do `JSON.parse` is a bad thing IMO. For the error list you can take inspiration from the current design. It has the `error.errors` array field, if it has a single error, then it is a single item list, otherwise it has multiple errors like validation failures.

2021-03-15 21:41 UTC, shlomi-nx reviewed
Looks good so far, see comments below

2021-03-15 21:50 UTC, nitesh-idnani1 commented on papiea-engine/__tests__/procedure_tests/procedures_api.test.ts
> +            const error_messages = JSON.parse(res.data.error.error_details.cause.cause.message)
Good observation but we should segregate this to a separate PR (adding helper modules for axios)

2021-03-15 21:53 UTC, nitesh-idnani1 commented on papiea-engine/src/intentful_core/entity_creation_strategies/constructor_entity_creation_strategy.ts
>                                     ctx.tracing_ctx)
Yes, I'm seeing we need a better representation for the Jaeger span. I'm working on this as part of the "Add log tags" (#575) issue. Let's discuss about this tomorrow.

2021-03-25 11:06 UTC, Emulebest requested changes
A few comments

2021-03-25 11:06 UTC, Emulebest commented on papiea-engine/src/intentful_engine/intent_resolver.ts
> +                    console.debug(`Failed to process onChange in update active watcher status for entity with uuid: ${entry_ref.entity_reference.uuid} and kind: ${entry_ref.entity_reference.kind} for
Why is this a `console.debug` and not a `logger.debug`?

2021-03-25 11:06 UTC, Emulebest commented on papiea-engine/src/auth/s2s.ts
> +            console.debug(`Failed to get user auth info for provider ${provider_prefix}/${provider_version} due to error: ${e}`)
Why is this a `console.debug` and not a `logger.debug`?

2021-03-25 11:06 UTC, Emulebest commented
Please also update this to latest master

2021-04-08 08:52 UTC, Emulebest approved these changes

2021-04-08 08:53 UTC, Emulebest commented
@nitesh-idnani1 please resolve merge conflicts and merge it in, thanks

2021-04-08 21:25 UTC, merged