Added validator check for untyped object not marked as status-only
nutanix/papiea pull request #651
Opened 2021-03-11 21:43 UTC by nitesh-idnani1

Closes #650

2021-03-12 12:28 UTC, Emulebest requested changes
Looks good, one change request pending

2021-03-12 12:28 UTC, Emulebest commented on papiea-engine/src/validator/index.ts
> +                            console.warn(`Field ${field_name + "/" + field} is an untyped object with no properties for kind: ${provider_prefix}/${provider_version}/${kind_name}. Please check if this
Please make this a logger warning instead of a console one

2021-03-15 21:36 UTC, shlomi-nx reviewed
See comments

2021-03-15 21:36 UTC, shlomi-nx commented on papiea-engine/src/validator/index.ts
> +                            logger.warn(`Field ${field_name + "/" + field} is an untyped object with no properties for kind: ${provider_prefix}/${provider_version}/${kind_name}. Please check if this
Perhaps add a recommendation that these type of fields should probably be `status-only`.

2021-03-15 21:36 UTC, shlomi-nx commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +
Where are the assertions?

2021-03-15 21:42 UTC, nitesh-idnani1 commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +
Since the check just generates a warning, there is no tangible way to assert the expected behavior

2021-03-17 16:26 UTC, merged