[Python] Fixed custom field and metadata extension bug for background task
nutanix/papiea pull request #661
Opened 2021-03-17 21:45 UTC by nitesh-idnani1

Closes #654

2021-03-17 21:45 UTC, nitesh-idnani1 commented
I've tested this as part of the e2e tests locally but haven't published any specific tests since I didn't want to disrupt the python e2e tests for now.

2021-03-25 11:11 UTC, Emulebest requested changes

2021-03-25 11:11 UTC, Emulebest commented on papiea-sdk/python/papiea/python_sdk.py
> +            await callback(entity.status.provider_fields)
Please make sure this is totally up to date with the Typescript version. As an example, the callback has `ctx` parameter now https://github.com/nutanix/papiea/blob/7f5bd471427f3cfafd3b215cc8e53407e61d9501/papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts#L498

2021-03-25 16:38 UTC, nitesh-idnani1 commented on papiea-sdk/python/papiea/python_sdk.py
> +            await callback(entity.status.provider_fields)
Okay, these changes were made in a different PR, I'll review the new PR and add the changes here. Thanks

2021-04-08 08:38 UTC, merged