Modified logic and design for update status operation
nutanix/papiea pull request #677
Opened 2021-04-07 18:51 UTC by nitesh-idnani1

Closes #665 
- Modified return type for update spec/status in client and engine.
- Added status hash initialization using the current status value.
- Added check in status db to verify the input hash against db hash value.
- Added error type for entity status conflict (stale hash value).
- Added tests to verify error for stale hash value in update status.

2021-04-09 23:11 UTC, joshua-berry-ntnx requested changes

2021-04-09 23:11 UTC, joshua-berry-ntnx commented on papiea-engine/src/databases/status_db_mongo.ts
> +                        "metadata.status_hash": current_status_hash,
Why is this in `$setOnInsert` and not `$set`? Seems like we would always want to write the new status hash on a `replace_status()`.

2021-04-09 23:11 UTC, joshua-berry-ntnx commented on papiea-engine/src/databases/status_db_mongo.ts
> +            if (err.code === 11000) {
Can you add a comment (or maybe a named constant) explaining what this error code is?

2021-04-09 23:11 UTC, joshua-berry-ntnx commented on papiea-engine/src/databases/status_db_mongo.ts
> +            if (err.code === 9) {
Same as above -- what's this error code?

2021-04-09 23:11 UTC, joshua-berry-ntnx commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +            await axios.post(`${ sdk.entity_url }/${ sdk.provider.prefix }/${ sdk.provider.version }/${ kind_name }/${ metadata.uuid }/procedure/moveX`, { x: 5 });
Do you expect this to fail? If it succeeds, your test will pass.

2021-04-13 08:30 UTC, Emulebest requested changes
Overall looks good, some small comments

2021-04-13 08:30 UTC, Emulebest commented on papiea-engine/src/intentful_core/entity_creation_strategies/entity_creation_strategy_interface.ts
> +        if (request_metadata.status_hash === undefined || request_metadata.status_hash === null) {
Agree

2021-04-13 08:30 UTC, Emulebest commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +            await axios.post(`${ sdk.entity_url }/${ sdk.provider.prefix }/${ sdk.provider.version }/${ kind_name }/${ metadata.uuid }/procedure/moveX`, { x: 5 });
Looks fine, as it has `assertions(1)` on top

2021-04-13 08:30 UTC, Emulebest commented on papiea-sdk/typescript/__tests__/sdk_tests/provider_sdk.test.ts
> +    test("Provider with kind level procedures update status with stale status hash should fail", async () => {
Can we have a counter part to this test somewhere close that deliberately succeeds?

2021-04-13 18:24 UTC, nitesh-idnani1 commented on papiea-engine/src/utils/utils.ts
> +}
This is an interface in object-hash, I can't import it directly here.

2021-04-13 22:21 UTC, joshua-berry-ntnx commented on papiea-engine/src/utils/utils.ts
> +}
To re-export, I think you can do something like:

```ts
export {getObjectHash: hash};
```

2021-04-14 00:32 UTC, joshua-berry-ntnx approved these changes
I'm OK with this being merged as-is but there are a couple follow-up items noted below we should take on before closing the parent issue. (These are just refactoring items, not correctness or public-facing API issues.)

2021-04-14 00:32 UTC, joshua-berry-ntnx commented on papiea-engine/src/databases/status_db_interface.ts
> +     * @returns Promise
I believe a lot of these @-directives are optional; let's leave them off unless we have some actual documentation for each of these things (e.g. what is the promised return value?)

2021-04-14 00:32 UTC, joshua-berry-ntnx commented on papiea-engine/src/databases/status_db_interface.ts
> +     * @returns Promise
Same as above

2021-04-14 00:32 UTC, joshua-berry-ntnx commented on papiea-engine/src/databases/utils/errors.ts
> +export class GraveyardConflictingEntityError extends SpecConflictingEntityError {
Is this only thrown for spec updates or is it thrown for status updates too? If both, we may need to either get rid of this as a separate error type or split it into SpecGraveyard and StatusGraveyard (which I'm also not too wild about since we have a weird combinatoric mix of types).

2021-04-14 00:32 UTC, joshua-berry-ntnx commented on papiea-engine/src/intentful_core/intentful_strategies/status_update_strategy.ts
> +    specDb: Spec_DB
It seems a bit weird to me that we are messing with spec at all here. I see below that we are only using it to fetch the spec to be included in the return value; is this something that could be done by the caller of the StatusUpdateStrategy?

2021-04-14 21:52 UTC, nitesh-idnani1 commented on papiea-engine/src/intentful_core/intentful_strategies/status_update_strategy.ts
> +    specDb: Spec_DB
"DifferUpdateStrategy" class was already using the spec db as part of it's extended member variable. I just modified that as part of the base class so that the other classes can use it as well, for reading spec in this case. However, if we want to avoid the use of spec db in these classes, we can pass the spec/metadata in the function input.

2021-04-14 22:19 UTC, nitesh-idnani1 commented on papiea-engine/src/databases/utils/errors.ts
> +export class GraveyardConflictingEntityError extends SpecConflictingEntityError {
Yes, this error suggest conflict with the deleted entity for the user. I think the name is correct, since we want the user to understand that the conflict is with the entity and not just the spec. I don't think we can put any check/restriction for status hash since that value is not passed by user but something that the engine generates initially.

2021-04-14 23:33 UTC, merged

2021-04-15 00:18 UTC, joshua-berry-ntnx commented on papiea-engine/src/intentful_core/intentful_strategies/status_update_strategy.ts
> +    specDb: Spec_DB
hm ok. I probably need to look at the code flow here a little more to understand the context. But like I mentioned, I'm OK with this for now.