Added support for HTTPS endpoints in papiea engine
nutanix/papiea pull request #681
Opened 2021-04-16 22:59 UTC by nitesh-idnani1

Closes #488
- Modified papiea client to send https requests to the engine.
- Modified all tests to use https endpoints.
- Modified express logic to create a HTTPS server on same port config.
- Modified python and typescript SDKs to send https requests.

2021-04-16 23:01 UTC, nitesh-idnani1 commented
Creating a draft PR, since few things need to be resolved before dev/master test runs.

- Auth tests are failing due to these changes, need some help debugging those.
- Need to deploy certificates for server & client on CircleCI environment.

2021-04-26 12:14 UTC, Emulebest commented
@nitesh-idnani1 what is the status of this PR? Have you solved the auth test problems?

2021-04-26 18:24 UTC, nitesh-idnani1 commented
> @nitesh-idnani1 what is the status of this PR? Have you solved the auth test problems?

Yes, I've solved that. You can start reviewing this one

2021-04-28 15:50 UTC, Emulebest requested changes

2021-04-28 15:50 UTC, Emulebest commented on papiea-client/src/entity_client.ts
> +export function kind_client(papiea_url: string, provider: string, kind: string, version: string, s2skey?: string, ca_path?: string, key_path?: string, cert_path?: string, tracer?: Tracer): EntityCRUD
Can we move `httpsAgent` to be save here once instead of passing it to all the functions?

2021-04-28 15:50 UTC, Emulebest commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> +                rejectUnauthorized: false
Are these tweakable? In production we should be able to set these to `true`

2021-04-28 20:10 UTC, nitesh-idnani1 commented on papiea-client/src/entity_client.ts
> +export function kind_client(papiea_url: string, provider: string, kind: string, version: string, s2skey?: string, ca_path?: string, key_path?: string, cert_path?: string, tracer?: Tracer): EntityCRUD
We need to pass it with the headers while making axios requests, can't do that here.

2021-04-28 20:13 UTC, nitesh-idnani1 commented on papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts
> +                rejectUnauthorized: false
We can use NODE_ENV variable to configure this, what do you suggest?

2021-04-28 22:25 UTC, joshua-berry-ntnx requested changes
In general we should never do `rejectUnauthorized: false` except in specific testing situations (and even then, IMO we shouldn't have to do it). Instead, I think the right thing to do is pass a proper CA (i.e. `ca.crt`) instead of setting `rejectUnauthorized`.

My concern about doing this even in tests is that someone else will later come along and see this, not realize its significance, and think it's a correct thing to do in shipping code (it very much is not). If we are "secure by default" even in our test/example code, hopefully we can save someone else some headache down the road.

I think most/all of my comments are about this one issue; also had a question about the oauth changes you made, see below.

2021-04-28 22:25 UTC, joshua-berry-ntnx commented on papiea-engine/src/auth/oauth2.ts
> +        },
Not sure I understand what this is doing / why it's needed. Can you explain? Why does oauth need its own HTTP agent?

Also, both `https` and `httpsAllowUnauthorized` seem to have the same settings.

2021-04-28 22:25 UTC, joshua-berry-ntnx commented on papiea-client/src/entity_client.ts
> +export function kind_client(papiea_url: string, provider: string, kind: string, version: string, s2skey?: string, ca_path?: string, key_path?: string, cert_path?: string, tracer?: Tracer): EntityCRUD
Same as above; let's pass the agent itself instead of the certs

2021-04-28 22:25 UTC, joshua-berry-ntnx commented on papiea-client/src/entity_client.ts
> +        rejectUnauthorized: false
Breaks HTTPS authentication as mentioned above

2021-05-05 00:10 UTC, nitesh-idnani1 commented on papiea-engine/src/auth/oauth2.ts
> +        },
Simple OAuth2 requires all three parameters, if we want to set a https agent.

2021-05-11 17:24 UTC, Emulebest approved these changes

2021-05-12 22:29 UTC, joshua-berry-ntnx requested changes
Looks mostly good apart from `install_certificates.sh`, where it seems we're unconditionally overwriting whatever certs are there (which is probably not what we want).

2021-05-12 22:29 UTC, joshua-berry-ntnx commented on papiea-engine/install_certificates.sh
> +cp -r ../python/e2e_tests/certs ./
Could we just symlink the entire `certs` dir wherever it's needed? Might be a little simpler than copying the individual files around

2021-05-12 22:29 UTC, joshua-berry-ntnx commented on papiea-engine/src/main.ts
> +    https.createServer({ key: privateKey, cert: certificate, request_cert: true }, app).listen(serverPort, function () {
I don't think we need to `request_cert: true` since we're not planning to authenticate the client.

2021-05-12 22:29 UTC, joshua-berry-ntnx commented on papiea-engine/start.sh
> +bash install_certificates.sh
If we're going to unconditionally generate certs, we should be checking at each step whether we need to generate that particular file, otherwise we will overwrite whatever the user has provided.

2021-05-12 22:29 UTC, joshua-berry-ntnx commented on papiea-engine/install_certificates.sh
> +openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 365 &&
As noted below, for each of these, we should be checking whether it already exists first.

2021-05-19 23:15 UTC, joshua-berry-ntnx approved these changes
LGTM. Since this is a breaking change, let's notify Customer-1 when it's merged.

2021-05-19 23:15 UTC, joshua-berry-ntnx commented on papiea-engine/install_certificates.sh
> +if [ ! -f server.crt ]; then
Also check for server.key

2021-05-20 18:06 UTC, merged